@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzkxNjI1OTR9.77al3w8vVvBW1TZo0k94G_e5Dgu7mMXMSdwBPfaHVVs
Post http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json


###

Get http://localhost:3000/orders/1.json
Authorization: Bearer {{jwt}}

###

Get http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}