Post http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Nzg4MTE0Mjd9.gTJLQ3p1q-Xl3BFAUxxzCA0TLNo6w7uGtV_1dW1EIzc
Content-Type: application/json

{
"product_id": 1,
"quantity": 1,
"subtotal": 15.00,
"tax": 1.50,
"total": 16.50
}

###

Get http://localhost:3000/orders/1.json

###

Get http://localhost:3000/orders.json