@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzkwNzUwMjB9.ZV5zpX66kG5g0BxpW6KwQC8nPSMbGBg_Nep4rOFKRM8
Post http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
"product_id": 1,
"quantity": 1
}

###

Get http://localhost:3000/orders/1.json
Authorization: Bearer {{jwt}}

###

Get http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}