@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzkwNzUwMjB9.ZV5zpX66kG5g0BxpW6KwQC8nPSMbGBg_Nep4rOFKRM8

@jwt_admin = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzkwNzUwMjB9.ZV5zpX66kG5g0BxpW6KwQC8nPSMbGBg_Nep4rOFKRM8

Get http://localhost:3000/products.json?category=Athletic


###

Get http://localhost:3000/products/2.json

###

Post http://localhost:3000/products.json
Authorization: Bearer {{jwt_admin}}
Content-Type: application/json

{
"name": "Ecco 1's",
"price": 25,
"description": "casual shoes that fit with most semiformal and casual outfits",
"quantity": 1

}

###

PATCH http://localhost:3000/products/6.json
Content-Type: application/json

{
 "price": 15.00
}

###

DELETE http://localhost:3000/products/4.json