@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Nzg4MjAwOTN9.9QWv0GfUejJ--ER38_D2v6AyU8XDCM_a6XR8-D6AWYM

@jwt_admin = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2Nzg4MjEwMDZ9.nZj3GJq0ZdMKZURGsVzd5rGqdAaX2V7NJUuqLuMS1a4

Get http://localhost:3000/products.json


###

Get http://localhost:3000/products/1.json

###

Post http://localhost:3000/products.json
Authorization: Bearer {{jwt_admin}}
Content-Type: application/json

{
"name": "Ecco 1's",
"price": 25,
"description": "casual shoes that fit with most semiformal and casual outfits",
"quantity": 1

}

###

PATCH http://localhost:3000/products/6.json
Content-Type: application/json

{
 "price": 15.00
}

###

DELETE http://localhost:3000/products/4.json