@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzkxNjI1OTR9.77al3w8vVvBW1TZo0k94G_e5Dgu7mMXMSdwBPfaHVVs
Post http://localhost:3000/users.json
Content-Type: application/json

{
"name": "Dwight Shrute",
"email": "D.S@example.com",
"password": "yoyo",
"password_confirmation": "yoyo"

}

###

Post http://localhost:3000/sessions.json
Content-Type: application/json

{
"email": "D.S@example.com",
"password": "yoyo"
}

###

Get http://localhost:3000/products.json
Authorization: Bearer {{jwt}}

Content-Type: application/json