@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Nzg4MjAwOTN9.9QWv0GfUejJ--ER38_D2v6AyU8XDCM_a6XR8-D6AWYM

Post http://localhost:3000/users.json
Content-Type: application/json

{
"name": "Dwight Shrute",
"email": "D.S@example.com",
"password": "yoyo",
"password_confirmation": "yoyo"

}

###

Post http://localhost:3000/sessions.json
Content-Type: application/json

{
"email": "josh.t@example.com",
"password": "password"
}

###

Get http://localhost:3000/products.json
Authorization: Bearer {{jwt}}

Content-Type: application/json